version: '3.7'
services:
  odoo:
    # 1. الصورة المبنية محلياً
    image: new_odoo_18_dockerfile:latest 
    restart: unless-stopped
    ports:
      # 2. ربط المنفذ الخارجي 8070 بالمنفذ الداخلي 8069 (المنفذ الافتراضي لـ Odoo)
      # تحديد IP المضيف لضمان ربط صحيح بالمنفذ (يمكن استبدال 192.168.88.106 بـ 0.0.0.0 إذا واجهت مشاكل)
      - "192.168.88.106:8070:8069" 
      
    # 3. تعيين المستخدم الصحيح (UID 100، GID 101) بناءً على النموذج الناجح في TrueNAS
    user: "100:101" 
    
    environment:
      # 4. إخبار Odoo باستخدام المنفذ 8069 داخلياً (لتجاوز أي تعارضات في الإعدادات)
      - ODOO_HTTP_PORT=8069 
      
      # 5. بيانات الاتصال بقاعدة البيانات الخارجية
      - HOST=192.168.88.106
      - USER=admin
      - PASSWORD=PASSWORD 
      - ODOO_DB_NAME=odoodb
      
      # 6. إعدادات Odoo الأخرى (Debugging, CORS, Modules)
      - ODOO_DEBUG_MODE=True       
      - ODOO_DEBUG=True
      - ODOO_DEV_MODE=True
      - ODOO_CORS_ORIGINS=*
      - ODOO_HTTP_CORS=*
      - ODOO_SERVER_WIDE_MODULES=base,web,rest_api_addon
      - ODOO_PROXY_MODE=True
      - ODOO_HTTP_ENABLE=True
      - ODOO_RC=/etc/odoo/odoo.conf
      - ODOO_LOG_LEVEL=debug
      - ODOO_LOG_HANDLER=:DEBUG
      - ODOO_LOG_DB=True
      - ODOO_LOG_DB_LEVEL=debug
      - ODOO_LOGFILE=/var/log/odoo/odoo.log

    volumes:
      # 7. مسارات البيانات الثابتة على Pool10T (يجب أن تكون الصلاحيات مضبوطة على 100:101)
      - /mnt/Pool10T/Odoo_Data/web-data:/var/lib/odoo
      - /mnt/Pool10T/Odoo_Data/addons:/mnt/extra-addons
      - /mnt/Pool10T/Odoo_Data/config:/etc/odoo
      - /mnt/Pool10T/Odoo_Data/logs:/var/log/odoo

      #  mkdir -p /mnt/Pool10T/Odoo_Data/web-data
      # mkdir -p /mnt/Pool10T/Odoo_Data/addons
      # mkdir -p /mnt/Pool10T/Odoo_Data/config
      # mkdir -p /mnt/Pool10T/Odoo_Data/logs
      # mkdir -p /mnt/Pool10T/Odoo_Data/postgresql-data
      # ضبط صلاحيات المجلدات لتتناسب مع المستخدم 100 والمجموعة 101
      # chown -R 100:101 /mnt/Pool10T/Odoo_Data
      # chmod -R 775 /mnt/Pool10T/Odoo_Data
    healthcheck:
      # 8. فحص الصحة للمنفذ 8069
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:8069' 
      interval: 30s
      timeout: 5s
      retries: 5
